version: '3.8'

services:
  # This is our main application service, where we will develop.
  app:
    # Build the image from the Dockerfile in the same directory
    build:
      context: .
      dockerfile: Dockerfile
    
    # Mount the entire project folder into the container's /workspace directory
    volumes:
      - ..:/workspace:cached

    # Set environment variables for the application
    environment:
      - GREETING=Hi there

    # Overrides the default command from the Dockerfile, if needed.
    # We keep the infinite loop to ensure the container stays running.
    command: /bin/sh -c "while sleep 1000; do :; done"

  # An example of a dependency service, like a database or cache.
  # This Redis container will be on the same network as our app.
  db:
    image: "redis:alpine"
    ports:
      - "6379:6379"
